// Option lists for the post-signup "Almost there" profile-enrichment
// step. Kept in one place so they're easy to edit later.

export const ROLE_OPTIONS = [
    "Judge",
    "Government Counsel or Court Officer",
    "Associate (A0-A1)",
    "Associate (A2-A3)",
    "Senior/Principal Associate (SA/PA/Counsel)",
    "Partner",
    "Managing Partner",
    "Independent Practitioner/Advocate",
    "Senior Advocate",
    "General Counsel (GC)",
    "In-House Counsel",
    "Compliance/Risk Officer",
    "Student",
    "Intern",
    "Chief Technology Officer/CDO/CIO",
    "Legal Technology",
    "Legal Operations",
    "Other",
] as const;

export const PRACTICE_TYPE_OPTIONS = [
    "Judicial",
    "Mixed Practice",
    "Disputes (Litigation, Arbitration, Mediation/ADR, etc.)",
    "Corporate, Commercial or Transactional Law",
    "Advisory",
    "In-House Counsel (Compliance, Risk, etc.)",
    "Academic",
    "Other",
] as const;

// All Indian states and union territories, sorted alphabetically,
// with "Other" last.
export const INDIAN_STATE_OPTIONS = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Other",
] as const;
