import type { Metadata } from "next";
import Link from "next/link";
import { SiteLogo } from "@/app/components/site-logo";

export const metadata: Metadata = {
    title: "Terms of Service – Gavel",
    description: "Terms of Service for the Gavel AI legal platform.",
};

function Section({
    number,
    title,
    children,
}: {
    number: string;
    title: string;
    children: React.ReactNode;
}) {
    return (
        <section className="space-y-3">
            <h2 className="text-xl font-medium font-serif text-gray-900">
                {number}. {title}
            </h2>
            <div className="space-y-3 text-sm leading-6 text-gray-700">
                {children}
            </div>
        </section>
    );
}

export default function TermsPage() {
    return (
        <div className="min-h-dvh bg-gray-50/80 px-6 py-10">
            <div className="mx-auto w-full max-w-3xl">
                <div className="mb-8 flex items-center justify-between">
                    <SiteLogo size="md" asLink />
                    <Link
                        href="/privacy"
                        className="text-sm text-gray-500 hover:text-gray-900 transition-colors"
                    >
                        Privacy Policy
                    </Link>
                </div>

                <h1 className="text-3xl font-medium font-serif text-gray-950 mb-2">
                    Terms of Service
                </h1>
                <p className="text-sm text-gray-500 mb-10">
                    Last updated: 11 July 2026
                </p>

                <div className="space-y-10 pb-16">
                    <Section number="1" title="Agreement">
                        <p>
                            These Terms of Service (&ldquo;Terms&rdquo;) govern
                            your access to and use of Gavel, an AI-assisted
                            legal document analysis, research, and drafting
                            platform (the &ldquo;Service&rdquo;), operated by
                            the Gavel team (&ldquo;we&rdquo;,
                            &ldquo;us&rdquo;, &ldquo;our&rdquo;). By creating
                            an account or using the Service you agree to be
                            bound by these Terms and by our{" "}
                            <Link
                                href="/privacy"
                                className="text-blue-600 hover:underline"
                            >
                                Privacy Policy
                            </Link>
                            . If you use the Service on behalf of a law firm or
                            other organisation, you represent that you are
                            authorised to bind that organisation, and
                            &ldquo;you&rdquo; includes that organisation.
                        </p>
                    </Section>

                    <Section number="2" title="Eligibility and Accounts">
                        <p>
                            The Service is intended for advocates, law firms,
                            in-house counsel, and other legal professionals and
                            their staff. You must be at least 18 years of age
                            and competent to contract under the Indian
                            Contract Act, 1872. You are responsible for
                            maintaining the confidentiality of your account
                            credentials and for all activity under your
                            account, and you must notify us promptly of any
                            unauthorised use.
                        </p>
                    </Section>

                    <Section number="3" title="Not Legal Advice">
                        <p>
                            Gavel is a productivity tool for legal
                            professionals. Output generated by the Service —
                            including analyses, summaries, drafts, case-law
                            search results, and citations —{" "}
                            <strong>
                                is generated by artificial intelligence, may
                                contain errors or omissions, and does not
                                constitute legal advice or legal opinion
                            </strong>
                            . No advocate-client relationship is created
                            between you (or your clients) and us. You retain
                            sole professional responsibility for reviewing,
                            verifying, and approving any output before relying
                            on it or providing it to a client, court,
                            tribunal, or authority, including verifying every
                            citation against the official source. Use of the
                            Service does not diminish your obligations under
                            the Advocates Act, 1961 and the Bar Council of
                            India rules on professional standards.
                        </p>
                    </Section>

                    <Section number="4" title="Your Content">
                        <p>
                            You retain all rights in documents, prompts, and
                            other material you upload to the Service
                            (&ldquo;Your Content&rdquo;) and in output
                            generated for you. You grant us a limited,
                            non-exclusive licence to host, process, and
                            transmit Your Content solely to provide the
                            Service, including transmitting relevant portions
                            to the third-party AI model providers and services
                            described in the Privacy Policy.
                        </p>
                        <p>
                            You are responsible for ensuring that you have the
                            right and any necessary consents — including, where
                            applicable, informed client consent — to upload and
                            process Your Content, particularly material that is
                            privileged, confidential, or contains personal
                            data of others. We do not use Your Content to
                            train AI models.
                        </p>
                    </Section>

                    <Section number="5" title="Acceptable Use">
                        <p>You must not use the Service to:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>
                                violate any applicable law, court order, or
                                professional conduct rule;
                            </li>
                            <li>
                                upload content that is unlawful, infringing,
                                or that you lack the right to process;
                            </li>
                            <li>
                                attempt to gain unauthorised access to the
                                Service, other accounts, or underlying
                                systems, or to probe or disrupt them;
                            </li>
                            <li>
                                resell, sublicense, or provide the Service to
                                third parties except to users within your
                                organisation;
                            </li>
                            <li>
                                use the Service to build a competing product
                                or scrape it at scale.
                            </li>
                        </ul>
                    </Section>

                    <Section number="6" title="Third-Party Services">
                        <p>
                            The Service relies on third-party infrastructure
                            and data sources, including AI model providers,
                            cloud hosting, database, storage services, and the
                            Indian Kanoon case-law database. Case-law and
                            statutory material retrieved from third-party
                            sources may be incomplete or out of date, and
                            those services may impose their own terms. We are
                            not responsible for the availability or accuracy
                            of third-party services.
                        </p>
                    </Section>

                    <Section number="7" title="Fees">
                        <p>
                            Where the Service (or any tier of it) is offered
                            for a fee, fees, billing cycles, and taxes
                            (including GST) will be communicated to you at or
                            before purchase. Except as required by law, fees
                            are non-refundable.
                        </p>
                    </Section>

                    <Section number="8" title="Availability and Changes">
                        <p>
                            We aim to keep the Service available at all times
                            but do not guarantee uninterrupted or error-free
                            operation. We may modify, suspend, or discontinue
                            features with reasonable notice where practicable.
                            We may update these Terms from time to time; the
                            updated version will be posted on this page with a
                            revised date, and your continued use of the
                            Service constitutes acceptance.
                        </p>
                    </Section>

                    <Section number="9" title="Disclaimer of Warranties">
                        <p>
                            The Service is provided on an &ldquo;as is&rdquo;
                            and &ldquo;as available&rdquo; basis. To the
                            maximum extent permitted by law, we disclaim all
                            warranties, express or implied, including
                            merchantability, fitness for a particular purpose,
                            accuracy, and non-infringement.
                        </p>
                    </Section>

                    <Section number="10" title="Limitation of Liability">
                        <p>
                            To the maximum extent permitted by law: (a) we are
                            not liable for any indirect, incidental, special,
                            consequential, or punitive loss, or for loss of
                            profits, business, goodwill, or data; and (b) our
                            aggregate liability arising out of or relating to
                            the Service shall not exceed the fees paid by you
                            for the Service in the twelve (12) months
                            preceding the claim or, where no fees were paid,
                            ₹10,000 (Rupees Ten Thousand). Nothing in these
                            Terms limits liability that cannot be limited
                            under applicable law.
                        </p>
                    </Section>

                    <Section number="11" title="Indemnity">
                        <p>
                            You will indemnify and hold us harmless from
                            claims, damages, and expenses (including
                            reasonable legal fees) arising out of Your
                            Content, your use of the Service in breach of
                            these Terms, or your violation of applicable law
                            or professional conduct rules.
                        </p>
                    </Section>

                    <Section number="12" title="Suspension and Termination">
                        <p>
                            You may stop using the Service and delete your
                            account at any time from the Account section. We
                            may suspend or terminate your access for material
                            breach of these Terms, unlawful use, or risk to
                            the Service or other users. On termination, your
                            right to use the Service ceases; data deletion and
                            export are handled as described in the Privacy
                            Policy.
                        </p>
                    </Section>

                    <Section number="13" title="Governing Law and Disputes">
                        <p>
                            These Terms are governed by the laws of India.
                            Subject to the arbitration provision below, the
                            courts at Mumbai, Maharashtra shall have exclusive
                            jurisdiction. Any dispute arising out of or in
                            connection with these Terms shall first be sought
                            to be resolved amicably; failing resolution within
                            30 days, it shall be referred to arbitration by a
                            sole arbitrator seated in Mumbai under the
                            Arbitration and Conciliation Act, 1996, conducted
                            in English.
                        </p>
                    </Section>

                    <Section number="14" title="Contact">
                        <p>
                            Questions about these Terms can be raised through
                            the{" "}
                            <Link
                                href="/support"
                                className="text-blue-600 hover:underline"
                            >
                                Support page
                            </Link>
                            .
                        </p>
                    </Section>
                </div>
            </div>
        </div>
    );
}
